#
# Message sent when the player doesnt have permission for
# a channel or any command of the plugin.
#
no_permission: '&cVocê não tem permissão!'

#
# Sent when the player tries to do chat without any text
#
channel_usage_message: '&cUso: /{command} <mensagem>'

#
# Text sent when plugin is reloaded
#
plugin_reloaded: '&aPlugin recarregado.'

#
# Enable or disable plugin components here
# Every module have its own configuration file
# so you will not get distracted with useless or unrelated
# things while setting up things.
#
modules:
    #
    # Chat color module
    # Players can choose their own chatcolor
    # either normal (&c) or hexadecimal (#4DC3FF)
    #
    chatcolor: true
    # Chat focus modules
    # Players can choose a chat to default speak on or
    # Optionally, force chat worlds can be set-up
    focus: true