no_permission: '&cVocê não tem permissão!'
channel_usage_message: '&cUso: /{command} <mensagem>'
plugin_reloaded: '&aPlugin recarregado.'
colors:
    only_players: '&cDisponível apenas para jogadores!'
    no_arg: '&cDigite uma cor! /chatcor #<cor>'
    removed: '&aVocê removeu sua cor de chat!'
    invalid: '&cDigite uma cor hexadecimal válida! /chatcor #<cor>'
    success: '&aAs cores do seu chat foram alteradas com sucesso!'