name: SimplexChat
version: 1.3.0
api-version: 1.13
main: me.luucx7.simplexchat.SimplexChat
author: Luucx7
depend: [PlaceholderAPI]
commands:
    chatcor:
        aliases: [chatcolor, corchat]
        permission: chat.colorido
    g:
        aliases: [global, globalchat]
        permission: chat.global