name: SimplexChat
version: 2.1.3
api-version: 1.13
main: me.luucx7.simplexchat.SimplexChat
author: Luucx7
depend: [PlaceholderAPI]
commands:
    chatcor:
        aliases: [chatcolor, corchat, colorchat]
    simplexchat:
