name: SimplexChat
version: 1.5.1
api-version: 1.16
main: me.luucx7.simplexchat.SimplexChat
author: Luucx7
depend: [PlaceholderAPI]
commands:
    chatcor:
        aliases: [chatcolor, corchat, colorchat]
        permission: chat.colorido
    simplexchat:
    